const PDFDocument = require('pdfkit');
const { humanizeDuration } = require('../utils/formatters');

/**
 * Generates an admin session report as a Node.js Buffer (pdfkit).
 */
function generateSessionPdf(summary, violations) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.fontSize(20).fillColor('#1e293b').text('ProctorX Session Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).fillColor('#334155').text(`Generated: ${new Date().toISOString()}`);
    doc.moveDown(0.5);

    const rule = (label, value) => {
      doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#0f172a').text(`${label}`, { continued: true });
      doc.font('Helvetica').fillColor('#334155').text(`  ${value}`);
    };

    rule('Candidate', `${summary.candidateName} (${summary.candidateId || 'N/A'})`);
    rule('Exam', summary.examTitle);
    rule('Status', `${summary.status}${summary.autoEnded ? ' (auto-ended)' : ''}`);
    rule('Duration', summary.duration || humanizeDuration(summary.durationSeconds));
    rule('Start', new Date(summary.startTime).toISOString());
    rule('End', summary.endTime ? new Date(summary.endTime).toISOString() : 'In progress');
    rule('Trust Score', `${summary.trustScore} / 100`);
    rule('Risk Level', summary.riskLevel);
    rule('Violations', String(summary.violationCount));
    rule('Face present / absent / multiple / looking away', [
      summary.facePresent, summary.faceAbsent, summary.faceMultiple, summary.lookingAway,
    ].join(' / '));
    rule('Browser active / inactive', `${summary.browserActive} / ${summary.browserInactive}`);
    rule('Remarks', summary.remarks);

    doc.moveDown(1);

    if (violations && violations.length) {
      doc.font('Helvetica-Bold').fontSize(13).fillColor('#0f172a').text('Violations');
      doc.moveDown(0.4);

      const tableTop = doc.y;
      const colWidths = [150, 70, 60, 220];
      const headers = ['Type', 'Severity', 'Points', 'Details'];

      doc.font('Helvetica-Bold').fontSize(9.5).fillColor('#334155');
      let x = 48;
      headers.forEach((h, i) => {
        doc.text(h, x, tableTop, { width: colWidths[i] });
        x += colWidths[i];
      });
      doc.moveDown(0.3);

      violations.slice(0, 40).forEach((v, idx) => {
        if (doc.y > 700) {
          doc.addPage();
        }
        const y = doc.y;
        doc.font('Helvetica').fontSize(9).fillColor('#475569');
        doc.text(v.type, 48, y, { width: colWidths[0] });
        doc.text(v.severity, 48 + colWidths[0], y, { width: colWidths[1] });
        doc.text(String(v.points), 48 + colWidths[0] + colWidths[1], y, { width: colWidths[2] });
        doc.text(v.message || '', 48 + colWidths[0] + colWidths[1] + colWidths[2], y, { width: colWidths[3] });
        doc.moveDown(0.4);
      });
    } else {
      doc.font('Helvetica').fontSize(11).fillColor('#475569').text('No violations recorded.');
    }

    doc.moveDown(1.5);
    doc.font('Helvetica').fontSize(8).fillColor('#94a3b8').text('Confidential - generated by ProctorX monitoring platform.', { align: 'center' });
    doc.end();
  });
}

module.exports = { generateSessionPdf };
